services:

  mongo:
    image: mongo:7
    container_name: mongo_apipedidos
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - apipedidos_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo_express_apipedidos
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    networks:
      - apipedidos_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_apipedidos
    restart: always
    ports:
      - "5672:5672"   # porta para aplicações
      - "15672:15672" # painel web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - apipedidos_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  apipedidos_network:
    driver: bridge

volumes:
  mongo_data:
  rabbitmq_data: