spring.application.name=api-pedidos

server.port=8084

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=bd-pedidos

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.rabbitmq.virtual-host=/